### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#10]
# Description

Various things to cleanup and get the codebase publishable.
# Tasks
- [x] Remove `requirements` as we do not need it (OKI coding standards)
- [x] Move `fixtures` into `tests`
- [x] Example json is broken: https://github.com/okfn/data-quality-cli/blob/master/dq-config.example.json#L3
- [x] `main` should only be for the CLI interface. Move utility functions to `utilities` ( https://github.com/okfn/data-quality-cli/blob/master/data_quality/main.py#L98 https://github.com/okfn/data-quality-cli/blob/master/data_quality/main.py#L111)
- [x] `utilities.compat` and `utilities.exception` should just be `compat` and `exception` at the top level of `data_quality`. `utilities` can just be a module, not a package.
- [ ] create a new `generate` package in the lib with a `ckan` module for https://github.com/okfn/data-quality-cli/issues/9
- [ ] Tests: the current test is a bit ridiculous. Would would be 5-6 useful unit tests for this library? Add them.
