### ISSUE TITLE
Refactoring "timeliness" as a dimension for assessment

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#13]
# Description

Timeliness of publication, along with Structure and Schema of the source files, is a dimension used in the assessment of data quality in the first dashboard we've developed for UK25k spend data https://github.com/okfn/data-quality-uk-25k-spend

However, timeliness is really hard to a) detect from the data available for a given data file, and b) to generalise for use over a range of different datasets we'd want to assess for quality.

Using the ideas we developed for the uk25k spend data, we need to address two points:
- Configuration of "timeliness" as a dimension for assessment
- Strategies for detecting "timely publication" for a given file
# Tasks
- [ ] Timeliness configuration (on `dq.json`)
  - [ ] Assess timeliness [ `assess_timeliness: False` ]: boolean. Whether to include timeliness as a dimension of the data quality assessment. Default to false.
  - [ ] Timeliness period [ `timeliness_period`: 1 ]: integer. The period of time in which a file publication can be considered timely. In months. Default 1.
  - [ ] Timeliness strategy [ `timeliness_strategy` ]: 'parse_filename'. The strategy to use to detect the period the data file applies to. One of `parse_filename`, `parse_property` (still TBD in detail)
    - [ ] Implement the parse filename strategy which should be able to be extracted from the uk25k spend codebase
- [ ] Apply the changes here to the uk25k spend data
- [ ] Tests

**Comment by pwalsh** [comment]
# Notes from @georgiana-b in https://github.com/okfn/data-quality-uk-25k-spend/issues/20

Currently `period_id` is [extracted from the title/url by the `period.py` script ](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/period.py#L13). This can go wrong [if the title has typos](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/period.py#L257) or if it doesn't contain all the necessary information (`https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/519924/_25K_March_Data.csv`) leading to empty or wrong `period_id` and errors in `data-quality-cli` performance calculation.
The need for `period.py` script is explained by the lack of `created` or `last_modified` fields for some resources. Ex from the CKAN API response:

``` py
[{'description': 'GTCE Spend April 2011 to January 2012',
  'format': 'CSV',
  'id': '0cdc2222-867c-4586-a5b4-6022a71b3cb6',
  'position': 0,
  'revision_id': '6773cab6-21b8-47c5-a02c-d5c71f23a151',
  'tracking_summary': {'recent': 0, 'total': 0},
  'url': 'http://media.education.gov.uk/assets/files/xls/gtce%20spend%20april%202011%20to%20january%202012.csv'},
 {'description': 'QCDA April 2010',
  'format': 'CSV',
  'id': 'f748cb1d-6e1b-4620-b996-3451ebfc9702',
  'position': 0,
  'revision_id': '6773cab6-21b8-47c5-a02c-d5c71f23a151',
  'tracking_summary': {'recent': 0, 'total': 0},
  'url': 'http://media.education.gov.uk/assets/files/xsl/qcda%20spend%20%20april%202010.csv'}]

```

Proposed solutions:
1. Ensure that `data-quality-cli` and (possibly) `data-quality-dashboard` are able to deal with empty periods. 
   - Pros:
     Tools will be more error-proof which is welcomed for the [new CKAN generator feature](https://github.com/okfn/data-quality-cli/pull/12).
     - Cons:
       According to the current implementation, each [entity in the dashboard](http://uk-25k.datadashboards.io/publishers/department-for-culture-media-and-sport) will have another row with an empty `Period`.
2. Use both `period_id` and  `created` fields and [improve the scoring algorithm](https://github.com/okfn/data-quality-cli/issues/5) to not score timeliness when any one these fields is unknown. This also makes sense since by using the period extracted from the title, `period_id` no longer refers to the time of upload but time covered by the data. As I understand timeliness, being on time would mean that the month of upload is ~=month covered by the data +1. So both period of creation and period covered by data should be known. This is closely related to okfn/data-quality-cli#13
   For example, the following would be cataloged as not timely: 

```
data,format,period_id,created_at
http://data.defra.gov.uk/ops/procurement/1204/EA-OVER-25K-1204.csv,csv,2012-04-01,2013-02-07T10:18:08.619710
```

I'll drop some numbers: 
Currently we have 1306 sources which is only a subset of UK CKAN.

By using this retrieval method: 

``` py
datafile['created_at'] = resource.get('created') or ast.literal_eval(resource.get('archiver',"{}")).get('created', '')
```

From 1306  resources, 374 rows have  `created` field null.
`revision_id` field is present in all of them which could be used to get the time of last update on CKAN. This however doesn't solve the problem if the concept of timeliness is what I explained above. 

There is only 1 field where `period_id` is null which is insignificant in the context of this app, but I think the above mentioned issues provide some important insights into how to make data-quality-cli/dashboard better.

# Notes from @pwalsh in https://github.com/okfn/data-quality-uk-25k-spend/issues/20

@georgiana-b 

( cc @akariv @amercader @jobarratt )

I've been thinking about timeliness, and how we can "score" it, and the related challenges.
- For timeliness, the datetime in `created` (from CKAN resources) is our best  indicator of **actual publication date**.
- Timeliness refers to the gap between when a dataset _should_ have been published, and when it was published
- When something _should_ have been published is hard to assess. Generally, we are referring to this as the "period" of the data (the period the data is relevant for)
- I see the following possibilities for knowing when a dataset "should have been" published, and each could be implemented as a different strategy for detecting the data period:
  - [ ] it is explicitly declared as a date/datetime on some object property ( easy, but does not reflect our current data )
  - [ ] it can be extracted from some object property ( parse string and throw relevant parts at the `dateutil` parser http://dateutil.readthedocs.io/en/stable/parser.html )
  - [ ] it can be extracted from the name of the resource file ( parse file name and throw relevant parts at the `dateutil` parser http://dateutil.readthedocs.io/en/stable/parser.html  - this is what we do right now for the UK 25k spend data)

Following, if none of the above strategies can be applied to a set of data in order to consistently build knowledge about the period the data belongs to, and the actual date the data was published, then, we cannot include "timeliness" as part of the scoring in such cases ( https://github.com/okfn/data-quality-cli/issues/13 ).

@georgiana-b for the case you outline above in solution 1. The case here is:
- we are measuring timeliness
- we use a "parse filename to extract period" strategy
- we have some cases (how many, exactly) where we cannot detect a period from the filename

So, in those cases, and those cases only, I think we should use `created` date as the period, thereby giving "benefit of the doubt" to the publishing body that the data is published in a timely manner. The caveat here is, if we are not detecting a period in more than, say, 10% of cases, we should really re-consider why timeliness is scored at all.

Thoughts?

**Comment by georgiana-b** [comment]
@pwalsh I agree with the workflow described in your checklist, except for `timeliness_strategy`. As far as I've seen in CKAN, most of the times there are multiple fields that can contain `period_id`. In `data-quality-uk-spend` [we use `title` (+ `description`) and `data`](https://github.com/okfn/data-quality-uk-25k-spend/blob/master/scripts/id_data.py#L240). So I think a safer way to go is have the `timeliness_strategy` be an array of multiple fields that should be analyzed, in order of priority. 
For example `timeliness_strategy: ['title', 'data']`  would mean:  
- Parse  `title` 
  - if you find something use it and stop
  - otherwise move to `data`.  
- If no `period_id` is found in any of the fields, I think we should use the strategy you described before:
  - Count the ones that don't have `period_id` and use `created` instead
  - If sources with empty `period_id` make 10% or more of the total:
    
    a. Tell the user about it, and ask if they want to continue anyway in a prompt and continue/stop based on the input.
    b. Raise and error asking them to make `assess_timeliness: False` because it's unreliable or add other fields that could contain it. 
  - If they don't, move on

For the "move on" part, it's unclear to me if I should incorporate this in the current scoring algorithm or just set up  the functionality described above and move on to #5. If I should incorporate it in the current one, how would it influence the score?

**Comment by pwalsh** [comment]
@georgiana-b 

ok, sounds good for a first take on this.

I do not want user interaction, so, if no `period_id` can be extracted from fields of more than 10% of sources (make the 10% configurable too), and if `assess_timeliness` is `True` (which it would be if you are making this check), then raise an error that tells the user that we cannot extract timeliness information for this set of data sources, and therefore they have to set `assess_timeliness` to `False`.
