### ISSUE TITLE
Describe database as a Data Package

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#15]
# Description

The "database" for a data quality dashboard consists of these files.
- `publishers.csv`
- `sources.csv`
- `runs.csv`
- `results.csv`
- `performance.csv`
- `instance.json` which holds metadata for a data quality dashboard that reads this database.

In various places in both the CLI and the web app for the dashboard, we read/write to this database and have hardcoded lists of column names, and we do not check for data types in columns and so on - exactly what Data Package and JSON Table Schema are for!
# Tasks
- [x] Write a `datapackage.json` template for a data quality database, with each of the data files (CSV) as a resource in the resources array, and the data from `instance.json` can be set directly on the `datapackage.json` file, replacing `instance.json` (although of course, for the template, these fields will be empty)
- [x] This file will live in (be packaged with) the codebase of the CLI (so, add to manifest. etc)
- [x] Use this for the various places in the code (of the CLI) where we get info on headers etc for a file (table) in the database
  -  [x] Use [datapackage-py](https://github.com/frictionlessdata/datapackage-py) and [jsontableschema-py](https://github.com/frictionlessdata/jsontableschema-py) to read/work with the `datapackage.json` (we'll use the JS equivalents when we get to the webapp)
- [x] The schema description in the [README](https://github.com/frictionlessdata/data-quality-cli#schema) can essentially be removed. Just give a brief overview, and a link to the `datapackage.json`
- [x] When generating a database, we copy this `datapackage.json` file into the new database along with the `publishers.csv` and `sources.csv'. The user then modifies her copy with the instance-specific info.
- [x] Add any extra tests required
## Minimal example

```
{
  "name": "",
  "resources": [
    {
      "path": "publishers.csv",
      "name": "publishers",
      "schema": {
            "fields": [
              {
                "name": "id",
                "title": "ID",
                "type": "string",
                "constraints": { "required": true, "unique": true }
              },
              {
                "name": "title",
                "title": "Title",
                "type": "string",
                "constraints": { "required": true, "unique": true }
              }
            ],
            "primaryKey": "id"
      }
    }
  ]
}
```
