### ISSUE TITLE
Refactor

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#4]
# Description

Changes to those codebase to support the hacks that were [made here](https://github.com/okfn/data-quality-uk-25k-spend). Specifically, this codebase has the concepts of task runners that are triggered both:
- After each pipeline runs on a single resource
- After the whole batch is run

These two hooks currently call tasks defined in `tasks.py` here. So, the tasks in `tasks.py` need to be extended to fit in all the new functionality that was added to ad hoc scripts [over there](https://github.com/okfn/data-quality-uk-25k-spend/issues/15) (`preprocess`?, `make_results`, `make_performance`).
# Tasks
- [x] Refer to the [OKI coding standards](https://github.com/okfn/coding-standards) and the [example codebase](https://github.com/okfn/oki-py) for Python style
- [x] Implement the extended use of `dq.json` to pass in arguments to both a [GoodTables Pipeline](https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/pipeline.py) and a [GoodTables Batch processor](https://github.com/okfn/goodtables/blob/master/goodtables/pipeline/batch.py) (See the code in this repo for how we call GoodTables).
- [x] Implement the various extras added over there as part of the task hooks here
- [x] Document the schema of the Data Quality database in a section of the readme titled "schema"

**Comment by pwalsh** [comment]
FIXED
