### ISSUE TITLE
Add a "generate" command

### ISSUE THREAD

**Issue by pwalsh** [okfn/spd-admin#9]
# Description

In https://github.com/okfn/data-quality-uk-25k-spend we have a very custom process to create a "database" for use in a Data Quality Dashboard. That is great, but there is clear scope to do something more generic, that is useful. We'll start with generating a base database from any CKAN instance.
# Tasks
- [ ] Add a `generate` command which takes two required arguments: `type` and `endpoint`
  - [ ] The API should look like: `dq generate ckan {url}`; `dq generate ckan https://data.qld.gov.au/`
- [ ] As a first pass, integrate the scripts that @k-nut wrote for us here: https://github.com/k-nut/ckan-data-quality
  - This will generate publishers and sources for the given endpoint.
- [ ] Check this against a number of public CKAN instances: some are listed here https://gist.github.com/pwalsh/3136548822909611c843
